## these shortcut keys work on any windows version
### alt+enter             = show property of any file
### alt+double click = show property of any file
### shift+right click  = appear 'copy as path' option

### ***but we have to upload our all csv files into google colab. uske baad hi we can work on csv files.***

In [4]:
# from google.colab import files
# uploaded = files.upload()


we can upload files using above code and we can directly mount our google drive into google colab by clicking on the folder icon that is located on the left hand side pane.

In [5]:
import pandas as pd
# these two lines that are mentioned below are compulsory to write so that all the rows and columns of the dataset we could see.
# if we don't write below lines then after some of the columns dot dot dot are shown to us.
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [6]:
# reading data from dataset in our local machine
# we can read data by uploading our dataset file in jupyter notebook.
# if we not write 'r' at the beginning of the dataset file path then we have to change backslashes (\) to forward-slashes (/).
# here 'df' is a variabe name for our dataset nad '.read' is a function in 'pandas' library to read data from any dataset file.
# we have given '_csv' beacause our file is in '.csv' format.
df=pd.read_csv('/content/drive/MyDrive/Datasets-main/CardioGoodFitness-1.csv')

In [7]:
# '.head()' gives only first 5 rows of our dataset, if we don't specify any parameter.
# if we specify the number of rows as the parameter of the method, it shows those specific number of rows.
# if we do not call '.head()' then it will show all the rows and columns of our dataset.
# '.head()' is basically used to check whether our dataset has colums and rows or not.
df.head(10)

  Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  Miles
0   TM195   18    Male         14        Single      3        4   29562    112
1   TM195   19    Male         15        Single      2        3   31836     75
2   TM195   19  Female         14     Partnered      4        3   30699     66
3   TM195   19    Male         12        Single      3        3   32973     85
4   TM195   20    Male         13     Partnered      4        2   35247     47
5   TM195   20  Female         14     Partnered      3        3   32973     66
6   TM195   21  Female         14     Partnered      3        3   35247     75
7   TM195   21    Male         13        Single      3        3   32973     85
8   TM195   21    Male         15        Single      5        4   35247    141
9   TM195   21  Female         15     Partnered      2        3   37521     85

In [8]:
# '.tail()' gives last 5 rows of our dataset
# it basically does the opposite of '.head()'.
df.tail(10)

,Product,Age,Gender,Education,MaritalStatus,Usage,Fitness,Income,Miles
170,TM798,31,Male,16,Partnered,6,5,89641,260
171,TM798,33,Female,18,Partnered,4,5,95866,200
172,TM798,34,Male,16,Single,5,5,92131,150
173,TM798,35,Male,16,Partnered,4,5,92131,360
174,TM798,38,Male,18,Partnered,5,5,104581,150
175,TM798,40,Male,21,Single,6,5,83416,200
176,TM798,42,Male,18,Single,5,4,89641,200
177,TM798,45,Male,16,Single,5,5,90886,160
178,TM798,47,Male,18,Partnered,4,5,104581,120
179,TM798,48,Male,18,Partnered,4,5,95508,180

In [9]:
# it gives us a random row from our dataset.
# if we specify a number as a parameter, then it will show those specific number of rows that are random from our dataset.
df.sample(5)

,Product,Age,Gender,Education,MaritalStatus,Usage,Fitness,Income,Miles
112,TM498,29,Female,14,Partnered,3,3,51165,95
136,TM498,40,Female,16,Single,3,3,57987,85
84,TM498,21,Female,14,Partnered,5,4,34110,212
111,TM498,27,Male,14,Single,4,2,45480,53
25,TM195,24,Male,13,Partnered,3,2,42069,47

In [10]:
# it basically shows the total number of (rows, columns) present in our dataset
df.shape

(180, 9)

In [11]:
# it basically shows the datatypes of all the columns present in our datset.
# here for string type names it gives 'object' datatype and for number it gives 'int64' datatype
df.dtypes

Product          object
Age               int64
Gender           object
Education         int64
MaritalStatus    object
Usage             int64
Fitness           int64
Income            int64
Miles             int64
dtype: object

In [12]:
# it basically shows all the information about our dataset i.e.,
# there is any blank column present or not etc. types information.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Product        180 non-null    object
 1   Age            180 non-null    int64
 2   Gender         180 non-null    object
 3   Education      180 non-null    int64
 4   MaritalStatus  180 non-null    object
 5   Usage          180 non-null    int64
 6   Fitness        180 non-null    int64
 7   Income         180 non-null    int64
 8   Miles          180 non-null    int64
dtypes: int64(6), object(3)
memory usage: 12.8+ KB

In [13]:
# check if any null or blank column is present in our dataset or not.
df.isnull().sum()

Product          0
Age              0
Gender           0
Education        0
MaritalStatus    0
Usage            0
Fitness          0
Income           0
Miles            0
dtype: int64

In [14]:
# it basically shows different mathematical values of our dataset.
# it only shows the mathematical values of those rows who has numbers of any type.
df.describe()

,Age,Education,Usage,Fitness,Income,Miles
count,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000
mean,28.788889,15.572222,3.455556,3.311111,53719.577778,103.194444
std,6.943498,1.617055,1.084797,0.958869,16506.684226,51.863605
min,18.000000,12.000000,2.000000,1.000000,29562.000000,21.000000
25%,24.000000,14.000000,3.000000,3.000000,44058.750000,66.000000
50%,26.000000,16.000000,3.000000,3.000000,50596.500000,94.000000
75%,33.000000,16.000000,4.000000,4.000000,58668.000000,114.750000
max,50.000000,21.000000,7.000000,5.000000,104581.000000,360.000000

In [15]:
# if we want all the description of dataset then :-
# here 'NaN' means 'Not a Number'.
# NaN is showing beacuse those values can't be calculated.
df.describe(include='all')

,Product,Age,Gender,Education,MaritalStatus,Usage,Fitness,Income,Miles
count,180,180.000000,180,180.000000,180,180.000000,180.000000,180.000000,180.000000
unique,3,NaN,2,NaN,2,NaN,NaN,NaN,NaN
top,TM195,NaN,Male,NaN,Partnered,NaN,NaN,NaN,NaN
freq,80,NaN,104,NaN,107,NaN,NaN,NaN,NaN
mean,NaN,28.788889,NaN,15.572222,NaN,3.455556,3.311111,53719.577778,103.194444
std,NaN,6.943498,NaN,1.617055,NaN,1.084797,0.958869,16506.684226,51.863605
min,NaN,18.000000,NaN,12.000000,NaN,2.000000,1.000000,29562.000000,21.000000
25%,NaN,24.000000,NaN,14.000000,NaN,3.000000,3.000000,44058.750000,66.000000
50%,NaN,26.000000,NaN,16.000000,NaN,3.000000,3.000000,50596.500000,94.000000
75%,NaN,33.000000,NaN,16.000000,NaN,4.000000,4.000000,58668.000000,114.750000
max,NaN,50.000000,NaN,21.000000,NaN,7.000000,5.000000,104581.000000,360.000000